In [1]:
# # create empty DataFrame df and append row
# my_cols = ['date', 'days_lookback', 'syms_freq', 'symbols']
# # Creating Empty DataFrame and Storing it in variable df
# df_model_top_picks = pd.DataFrame(columns=my_cols)
# df_model_top_picks

In [2]:
import pandas as pd
from myUtils import pickle_load, pickle_dump
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 30)
pd.set_option('display.max_colwidth', 30)
pd.set_option('display.width', 900)

path_dir = "C:/Users/ping/MyDrive/stocks/yfinance/"
path_data_dump = path_dir + "VSCode_dump/"

fp_df_picks  = f'df_picks'
fp_df_model_top_picks = f'df_model_top_picks'

In [3]:
df = pickle_load(path_data_dump, fp_df_picks)
df = df.drop_duplicates(subset=['date_end_df_train', 'max_days_lookbacks', 'days_lookbacks'], keep='last')
df = df.sort_values(by=['date_end_df_train', 'max_days_lookbacks', 'days_lookbacks'], ascending=False)
df = df.reset_index(drop=True)
pickle_dump(df, path_data_dump, fp_df_picks)
print(f'len(df): {len(df)}')
print(df)

len(df): 34
   date_end_df_train  max_days_lookbacks     days_lookbacks sym_freq_15 sym_freq_14 sym_freq_13 sym_freq_12      sym_freq_11      sym_freq_10        sym_freq_9              sym_freq_8                    sym_freq_7                     sym_freq_6                     sym_freq_5                     sym_freq_4                     sym_freq_3 sym_freq_2
0         2023-04-06                 120      [30, 60, 120]          []          []          []          []               []               []                []                 ['SHV']                      ['FTSM']                ['ELF', 'SGEN']       ['META', 'NVDA', 'PDFS']  ['ACLS', 'AMPH', 'AU', 'GB...    ['AJRD', 'ANET', 'BTC-USD']         []
1         2023-04-06                 120  [15, 30, 60, 120]          []          []          []          []               []               []                []                 ['SHV']                ['AU', 'FTSM']  ['ELF', 'NVO', 'SGEN', 'SNY']       ['META', 'NVDA', 'PDFS']  ['ACLS', 'AMP

In [4]:
from itertools import product
from ast import literal_eval

my_cols = ['sym_freq_12', 'sym_freq_9', 'sym_freq_8']
my_days_lookbacks = [[30, 60, 120], [15, 30, 60, 120]]

my_dates = []
for my_days_lookback in my_days_lookbacks:
  my_row = (df['days_lookbacks'] == str(my_days_lookback))
  l_dates = df.loc[my_row, 'date_end_df_train'].tolist()     
  my_dates.append(l_dates)

my_dates = [val for sublist in my_dates for val in sublist]
my_dates = sorted(list(set(my_dates)), reverse=True)

d_lbk_freq = list(product(my_dates, my_days_lookbacks, my_cols))

picks = []
prev_date = ''
# print(f'Model predicts the best performing symbols are:\n[30, 60, 120]        sym_freq_9\n[15, 30, 60, 120]    sym_freq_12\n[30, 60, 120]        sym_freq_8')
print(f'Model predicts the best performing symbols are:')
print(f'1st    {"[30, 60, 120]":<20}{"sym_freq_9":<14}{"days_eval = 4":<20}')
print(f'2nd    {"[15, 30, 60, 120]":<20}{"sym_freq_12":<14}{"days_eval = 5":<20}')
print(f'3rd    {"[30, 60, 120]":<20}{"sym_freq_8":<14}{"days_eval = 4":<20}')
for i, item in enumerate(d_lbk_freq):
  my_date, my_days_lookback, my_col = item[0], item[1], item[2]
  my_row = (df['date_end_df_train'] == my_date) & (df['days_lookbacks'] == str(my_days_lookback))  
  list_in_df = df.loc[my_row, my_col]
  my_str = list_in_df.tolist()[0]
  my_list = literal_eval(my_str)
  blank = ' '
  if my_date != prev_date:
    if prev_date == '':
      print('\nModel Results:')  
      print(f'{i:<6}{my_date:<14}{str(my_days_lookback):<21}{my_col:<11}: {my_list}')
    else:
      print(f'\n{i:<6}{my_date:<14}{str(my_days_lookback):<21}{my_col:<11}: {my_list}') 
  else:
    print(f'{i:<6}{blank:<14}{str(my_days_lookback):<21}{my_col:<11}: {my_list}')

  picks.append((i, my_list))
  prev_date = my_date

Model predicts the best performing symbols are:
1st    [30, 60, 120]       sym_freq_9    days_eval = 4       
2nd    [15, 30, 60, 120]   sym_freq_12   days_eval = 5       
3rd    [30, 60, 120]       sym_freq_8    days_eval = 4       

Model Results:
0     2023-04-06    [30, 60, 120]        sym_freq_12: []
1                   [30, 60, 120]        sym_freq_9 : []
2                   [30, 60, 120]        sym_freq_8 : ['SHV']
3                   [15, 30, 60, 120]    sym_freq_12: []
4                   [15, 30, 60, 120]    sym_freq_9 : []
5                   [15, 30, 60, 120]    sym_freq_8 : ['SHV']

6     2023-04-05    [30, 60, 120]        sym_freq_12: []
7                   [30, 60, 120]        sym_freq_9 : ['SHV']
8                   [30, 60, 120]        sym_freq_8 : []
9                   [15, 30, 60, 120]    sym_freq_12: []
10                  [15, 30, 60, 120]    sym_freq_9 : ['SHV']
11                  [15, 30, 60, 120]    sym_freq_8 : []

12    2023-04-04    [30, 60, 120]        sym

In [5]:
model_top_picks = [([30, 60, 120], 'sym_freq_9'), ([15, 30, 60, 120], 'sym_freq_12'), ([30, 60, 120], 'sym_freq_8')]

In [6]:
df_model_top_picks = pickle_load(path_data_dump, fp_df_model_top_picks)

z_items   = zip(d_lbk_freq, picks)
for i, item in enumerate(z_items):
  _date, _days_lookback, _sym_freq, _syms = item[0][0], item[0][1], item[0][2], item[1][1]
  print(i, _date, _days_lookback, _sym_freq, _syms)
  dlb_sym_freq = (_days_lookback, _sym_freq)
  if dlb_sym_freq in model_top_picks and _syms:
    row_add = [_date, _days_lookback, _sym_freq, _syms]
    df_model_top_picks.loc[len(df_model_top_picks)] = row_add
    print(f'added row to df_model_top_picks:\n{row_add}\n')


0 2023-04-06 [30, 60, 120] sym_freq_12 []
1 2023-04-06 [30, 60, 120] sym_freq_9 []
2 2023-04-06 [30, 60, 120] sym_freq_8 ['SHV']
added row to df_model_top_picks:
['2023-04-06', [30, 60, 120], 'sym_freq_8', ['SHV']]

3 2023-04-06 [15, 30, 60, 120] sym_freq_12 []
4 2023-04-06 [15, 30, 60, 120] sym_freq_9 []
5 2023-04-06 [15, 30, 60, 120] sym_freq_8 ['SHV']
6 2023-04-05 [30, 60, 120] sym_freq_12 []
7 2023-04-05 [30, 60, 120] sym_freq_9 ['SHV']
added row to df_model_top_picks:
['2023-04-05', [30, 60, 120], 'sym_freq_9', ['SHV']]

8 2023-04-05 [30, 60, 120] sym_freq_8 []
9 2023-04-05 [15, 30, 60, 120] sym_freq_12 []
10 2023-04-05 [15, 30, 60, 120] sym_freq_9 ['SHV']
11 2023-04-05 [15, 30, 60, 120] sym_freq_8 []
12 2023-04-04 [30, 60, 120] sym_freq_12 []
13 2023-04-04 [30, 60, 120] sym_freq_9 []
14 2023-04-04 [30, 60, 120] sym_freq_8 ['NVDA', 'SHV']
added row to df_model_top_picks:
['2023-04-04', [30, 60, 120], 'sym_freq_8', ['NVDA', 'SHV']]

15 2023-04-04 [15, 30, 60, 120] sym_freq_12 []
16

In [7]:
df_model_top_picks = df_model_top_picks.astype(str)
df_model_top_picks = df_model_top_picks.drop_duplicates(keep='last')
df_model_top_picks = df_model_top_picks.sort_values(by=['date', 'days_lookback', 'syms_freq'], ascending=False)
df_model_top_picks = df_model_top_picks.reset_index(drop=True)
pickle_dump(df_model_top_picks, path_data_dump, fp_df_model_top_picks)
print(f'len(df_model_top_picks): {len(df_model_top_picks)}')
print(f'{fp_df_model_top_picks}:\n{df_model_top_picks}')

len(df_model_top_picks): 22
df_model_top_picks:
          date  days_lookback   syms_freq          symbols
0   2023-04-06  [30, 60, 120]  sym_freq_8          ['SHV']
1   2023-04-05  [30, 60, 120]  sym_freq_9          ['SHV']
2   2023-04-04  [30, 60, 120]  sym_freq_8  ['NVDA', 'SHV']
3   2023-04-03  [30, 60, 120]  sym_freq_8   ['GE', 'NVDA']
4   2023-03-31  [30, 60, 120]  sym_freq_8         ['NVDA']
5   2023-03-30  [30, 60, 120]  sym_freq_9          ['SHV']
6   2023-03-30  [30, 60, 120]  sym_freq_8         ['NVDA']
7   2023-03-29  [30, 60, 120]  sym_freq_9          ['SHV']
8   2023-03-28  [30, 60, 120]  sym_freq_9          ['SHV']
9   2023-03-27  [30, 60, 120]  sym_freq_9          ['SHV']
10  2023-03-27  [30, 60, 120]  sym_freq_8           ['GE']
11  2023-03-24  [30, 60, 120]  sym_freq_8  ['NVDA', 'SHV']
12  2023-03-23  [30, 60, 120]  sym_freq_9          ['SHV']
13  2023-03-22  [30, 60, 120]  sym_freq_9          ['SHV']
14  2023-03-22  [30, 60, 120]  sym_freq_8         ['FTSM']
15  2023

In [ ]:
df_mp = df_model_top_picks.copy()

In [126]:
sorted(df_c.index)[:10]
# sorted(df_c.index)[-10:]

[Timestamp('2017-04-24 00:00:00'),
 Timestamp('2017-04-25 00:00:00'),
 Timestamp('2017-04-26 00:00:00'),
 Timestamp('2017-04-27 00:00:00'),
 Timestamp('2017-04-28 00:00:00'),
 Timestamp('2017-05-01 00:00:00'),
 Timestamp('2017-05-02 00:00:00'),
 Timestamp('2017-05-03 00:00:00'),
 Timestamp('2017-05-04 00:00:00'),
 Timestamp('2017-05-05 00:00:00')]

In [130]:
print(f'len(df_c): {len(df_c)}')

# my_date = '2023-04-06'
my_date = '2017-04-24'

if my_date in df_c.index:  # there is a edge case where my_date is not in index, but the next date is in index 
  my_date_iloc = df_c.index.get_loc(my_date)
  next_date_iloc = my_date_iloc + 1
  print(f'len(df_c): {len(df_c)}, my_date_iloc: {my_date_iloc}, next_date_iloc: {next_date_iloc}')
  if my_date_iloc >= len(df_c) - 1:
    print(f'next_date_iloc: {next_date_iloc}, It is out-of-bounds. The max. iloc is {len(df_c) - 1}')
  else:
    row_next_date = df_c.iloc[next_date_iloc]
    print(f'row_next_date:\n{row_next_date}')
else:
  print(f'ERROR: my_date: {my_date} is not in df_c.index')


len(df_c): 1500
len(df_c): 1500, my_date_iloc: 0, next_date_iloc: 1
row_next_date:
A        52.352112
AA       36.077793
AAL      45.140968
AAP     136.706802
AAPL     33.909443
           ...    
ZION     34.756897
ZTO      12.349427
ZTS      53.150005
ZUMZ     18.350000
ZWS      23.325800
Name: 2017-04-25 00:00:00, Length: 1319, dtype: float64


In [86]:
import numpy as np
from ast import literal_eval
z_date_syms = zip(df_mp.date, df_mp.symbols)
portf_target = 1000  # ideal value of initial portfolio amount 
for _date, _syms in z_date_syms:
    l_syms = literal_eval(_syms)  # convert list stored as str back to list
    # print(_date, _syms, type(_date), type(_syms))
    ar_price = df_c.loc[_date][l_syms].values
    sym_cnt = len(l_syms)
    # print(_date, l_syms, ar_price, sym_cnt)
    amt_per_sym = portf_target / sym_cnt
    ar_sym_share = np.floor(amt_per_sym / ar_price)
    ar_sym_amt = ar_price * ar_sym_share
    portf_amt = sum(ar_sym_amt)
    print(_date, l_syms, ar_price, sym_cnt, ar_sym_share, ar_sym_amt, portf_amt)    



2023-04-06 ['SHV'] [110.19999695] 1 [9.] [991.79997253] 991.7999725341797
2023-04-05 ['SHV'] [110.19999695] 1 [9.] [991.79997253] 991.7999725341797
2023-04-04 ['NVDA', 'SHV'] [274.52999878 110.13999939] 2 [1. 4.] [274.52999878 440.55999756] 715.0899963378906
2023-04-03 ['GE', 'NVDA'] [ 96.91999817 279.6499939 ] 2 [5. 1.] [484.59999084 279.6499939 ] 764.2499847412109
2023-03-31 ['NVDA'] [277.76998901] 1 [3.] [833.30996704] 833.3099670410156
2023-03-30 ['SHV'] [110.09902954] 1 [9.] [990.89126587] 990.8912658691406
2023-03-30 ['NVDA'] [273.82998657] 1 [3.] [821.48995972] 821.4899597167969
2023-03-29 ['SHV'] [110.07910156] 1 [9.] [990.71191406] 990.7119140625
2023-03-28 ['SHV'] [110.06913757] 1 [9.] [990.62223816] 990.6222381591797
2023-03-27 ['SHV'] [110.05917358] 1 [9.] [990.53256226] 990.5325622558594
2023-03-27 ['GE'] [93.30999756] 1 [10.] [933.09997559] 933.0999755859375
2023-03-24 ['NVDA', 'SHV'] [267.79000854 110.05917358] 2 [1. 4.] [267.79000854 440.23669434] 708.0267028808594
2023

NameError: name 'date' is not defined

In [67]:
def portf_val(date, l_symbols):
#   _date = '2023-04-06'
#   _syms = ['FTSM', 'SHV']
  ar_price = df_c.loc[date][l_symbols].values
  print(ar_price, len(ar_price))

In [ ]:
# df['col_3'] = df.apply(lambda x: f(x.col_1, x.col_2), axis=1)
df_mp.apply(lambda x: portf_val(df_mp.date, df_mp.symbols), axis=0)

In [11]:
_date = '2023-04-06'
_syms = ['FTSM', 'SHV']
ar_price = df_c.loc['2023-04-06'][['FTSM', 'SHV']].values
print(ar_price, len(ar_price))

[ 59.59000015 110.19999695] 2


In [8]:
df = pickle_load(path_data_dump, fp_df_model_top_picks)

In [9]:
df_c = pickle_load(path_data_dump, 'df_close_clean')

In [10]:
df_c.tail()

A         AA    AAL         AAP        AAPL         AB        ABB        ABBV         ABC        ABM    ABR         ABT       ACGL       ACHC       ACIW  ...       XRAY    XRX         XYL       YELP       YUMC         YY         ZBH        ZBRA         ZD         ZG       ZION        ZTO         ZTS       ZUMZ        ZWS
Date                                                                                                                                                                           ...                                                                                                                                                                     
2023-03-31  138.114990  42.560001  14.75  121.610001  164.899994  36.560001  34.299999  159.369995  160.110001  44.712662  11.49  101.260002  67.870003  72.250000  26.980000  ...  39.279999  15.40  104.699997  30.700001  63.389999  31.180000  129.199997  318.000000  78.050003  43.700001  29.930000  28.291159  166.440002  18.440001  21.360001
2023-04-03  137.860001  41.770000  14.42  122.690002  166.169998  35.700001  34.419998  160.419998  162.279999  44.712662  11.46  101.589996  68.610001  72.550003  26.530001  ...  39.110001  15.09  104.459999  30.760000  64.019997  32.110001  128.039993  311.649994  77.800003  43.950001  29.120001  28.271416  167.660004  18.950001  21.440001
2023-04-04  138.210007  40.340000  14.16  121.339996  165.630005  34.810001  33.910000  159.779999  162.970001  43.270000  11.25  102.800003  67.889999  71.639999  26.180000  ...  38.970001  14.64  101.180000  30.740000  62.980000  31.280001  127.919998  308.709991  76.510002  43.299999  27.709999  28.380001  167.070007  18.510000  20.610001
2023-04-05  138.089996  39.430000  13.89  120.209999  163.759995  34.119999  33.110001  160.800003  167.360001  43.349998  11.21  104.209999  68.589996  72.639999  25.900000  ...  39.230000  14.38  100.269997  30.610001  62.549999  30.000000  128.589996  300.149994  75.809998  42.810001  28.629999  28.270000  167.649994  18.309999  20.219999
2023-04-06  138.029999  39.160000  14.01  120.690002  164.660004  34.110001  33.020000  161.550003  166.350006  43.840000  10.95  104.930000  68.940002  72.760002  26.059999  ...  39.540001  14.39  100.260002  30.990000  62.570000  30.230000  129.169998  300.260010  76.699997  43.919998  29.389999  28.670000  168.940002  18.459999  20.090000

[5 rows x 1319 columns]

In [12]:
import numpy as np
ar_sh = np.floor(1000 / ar_price)
ar_sh

array([16.,  9.])

In [13]:
ar_amt = ar_sh * ar_price
ar_amt

array([953.44000244, 991.79997253])

In [14]:
import numpy as np
np.floor(ar_sh)

array([16.,  9.])

In [15]:
df.tail()

date  days_lookback   syms_freq          symbols
17  2023-03-20  [30, 60, 120]  sym_freq_9  ['FTSM', 'SHV']
18  2023-03-17  [30, 60, 120]  sym_freq_9  ['FTSM', 'SHV']
19  2023-03-17  [30, 60, 120]  sym_freq_8           ['GE']
20  2023-03-16  [30, 60, 120]  sym_freq_9  ['FTSM', 'SHV']
21  2023-03-15  [30, 60, 120]  sym_freq_9  ['FTSM', 'SHV']